[mypy]
python_version = 3.14
mypy_path = packages:~/.config/mypy/stubs
ignore_missing_imports = True
show_error_codes = True
warn_unreachable = True
disallow_untyped_defs = True
disallow_untyped_calls = True
plugins =
    mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "django_stub_settings"
