[loggers]
keys=root

[handlers]
keys=console

[formatters]
keys=formatter

[logger_root]
level=DEBUG
handlers=console

[handler_console]
class=StreamHandler
level=DEBUG
formatter=formatter
args=(sys.stdout,)

[formatter_formatter]
format=%(asctime)s|%(levelname)s| %(message)s
datefmt=%Y-%m-%d %H:%M:%S
