#!/usr/bin/env app python
# -*- coding: utf-8 -*-
import my_apps
import plural_ru


class Workout_Rest(my_apps.App):
    def run(self):
        self.growlnotify(t="Перерыв")
        self.say("Перерыв начался")
        m = 0
        while self.sleep(1):
            if m != self.elapsed.minutes:
                m = self.elapsed.minutes
                ru = plural_ru.ru(m, ["минуту", "минуты", "минут"])
                self.say("Перерыв длится %s %s" % (m, ru))
                self.growlnotify(t="%s Перерыв" % m)


if __name__ == "__main__":
    Workout_Rest().run()
