#!/usr/bin/env log-exec bash

IFS=
# LC_ALL required for non english paths
[ -e ~/.bashrc ] && { set -x; . ~/.bashrc; { set +x; } 2>/dev/null; }

selection="$(set -x; finder-selection)" || exit
while IFS= read path; do
    ! [ -d "$path" ] && continue
    cd "$path" || exit
    ( set -x; repo:deprecate ) || exit
done <<< "$selection";:
