[global]
index-url =
    https://mirrors.aliyun.com/pypi/simple/
extra-index-url =
    https://pypi.tuna.tsinghua.edu.cn/simple/
    https://mirrors.ustc.edu.cn/pypi/simple/
    https://mirror.baidu.com/pypi/simple/
    https://mirrors.cloud.tencent.com/pypi/simple/
trusted-host =
    mirrors.aliyun.com
    pypi.tuna.tsinghua.edu.cn
    mirrors.ustc.edu.cn
    mirror.baidu.com
    mirrors.cloud.tencent.com
timeout = 120
retries = 5
root-user-action = ignore
