#!/usr/bin/env log-exec bash

IFS=
# LC_ALL required for non english paths
[ -e ~/.bashrc ] && { set -x; . ~/.bashrc; { set +x; } 2>/dev/null; }

cd "$(set -x; finder-selection)" || exit

( set -x; repo:files:rm ) || exit
( set -x; repo:admin ) || exit
( set -x; repo:files:init ) || exit
( set -x; repo:files:node:recreate ) || exit
( set -x; repo:files:python:recreate ) || exit

