[loggers]
keys=root

[handlers]
keys=console

[formatters]
keys=simple

[logger_root]
level=%(log_level)s
handlers=console

[handler_console]
class=StreamHandler
level=DEBUG
formatter=simple
args=(sys.stdout,)

[formatter_simple]
format=[%(levelname)s %(asctime)s %(module)s] %(message)s
