#!/usr/bin/env log-exec bash

IFS=
# LC_ALL required for non english paths
[ -e ~/.bashrc ] && { . ~/.bashrc || exit; }

path="$(finder-selection)" || exit

! [ -e "$path" ] && exit
[ -d "$path" ] && { open -a /Applications/Utilities/Terminal.app "$path" || exit; }
[ -f "$path" ] && { open -a /Applications/Utilities/Terminal.app "${path%/*}" || exit; };:
