#!/usr/bin/env bash
{ set +x; } 2>/dev/null

min=10

say "Яйца нужно положить в кипящую воду и варить 10 минут" &

while :; do
    s="$(pid-elapsed --seconds $$)" || exit
    m="$(pid-elapsed --minutes $$)" || exit

    [[ $m -gt $min ]] &&[[ $(($s%60)) == 0 ]] && {
        say "Яйца варятся уже [[ru:minutes $m]]" || exit
        growlnotify -t "Яйца" -m "$m:00" -s || exit
    }
    sleep 1
done;:

