port = 5432

# repl CLIENT config
max_worker_processes = 48
max_logical_replication_workers = 20
max_sync_workers_per_subscription = 2

max_wal_size = 1GB
min_wal_size = 80MB

max_locks_per_transaction = 10000

shared_preload_libraries = 'pg_stat_statements'
synchronous_commit = off

logging_collector=on
log_timezone = 'Europe/Moscow'

datestyle = 'iso, mdy'
timezone = 'Europe/Moscow'

lc_messages = 'en_US.UTF-8'		# locale for system error message
lc_monetary = 'en_US.UTF-8'		# locale for monetary formatting
lc_numeric = 'en_US.UTF-8'		# locale for number formatting
lc_time = 'en_US.UTF-8'			# locale for time formatting

default_text_search_config = 'pg_catalog.simple'

logging_collector = off
log_min_messages = warning
log_statement = 'none'
log_connections = on
log_replication_commands = on
log_error_verbosity = verbose
