#!/usr/bin/env bash
{ set +x; } 2>/dev/null

min=2

while :; do
    s="$(pid-elapsed --seconds $$)" || exit
    m="$(pid-elapsed --minutes $$)" || exit

    [[ $m -gt $min ]] &&[[ $(($s%60)) == 0 ]] && {
        say "Чайник кипятится уже [[ru:minutes $m]]" || exit
        growlnotify -t "Чайник" -m "$m:00" -s || exit
    }
    sleep 1
done;:
