port = 5446

# WAL
wal_level = 'logical'
max_wal_size = 1GB
min_wal_size = 80MB

max_locks_per_transaction = 10000

shared_preload_libraries = 'pg_stat_statements'
synchronous_commit = off

logging_collector=off
log_timezone = 'Europe/Moscow'

datestyle = 'iso, mdy'
timezone = 'Europe/Moscow'

lc_messages = 'en_US.UTF-8'     # locale for system error message
lc_monetary = 'en_US.UTF-8'     # locale for monetary formatting
lc_numeric = 'en_US.UTF-8'      # locale for number formatting
lc_time = 'en_US.UTF-8'         # locale for time formatting

default_text_search_config = 'pg_catalog.simple'


