#!/usr/bin/env log-exec bash

IFS=
set --
selection="$(set -x; . "${BASH_SOURCE[0]%/*}"/selection.sh)" || exit

[[ -n "$selection" ]] && while IFS= read path; do
    [ -d "$path" ] || continue
    fullname="$(awk -F/ '{print $(NF-1)"/"$(NF)}' <<< "$path")"
    url="https://github.com/$fullname"
    set -- "$@" "$url"
done <<< "$selection"
[[ $# != 0 ]] && { ( set -x; open "$@" ) || exit; };:

